default: clean

copy:
	cc copy.c -o copy

cat:
	cc cat.c -o cat

showAllContents:
	cc showAllContents.c -o showAllContents

clean:
	rm *.o *.out copy cat showAllContents prac2 *.txt prac3 prac3_nomutex thread_incr_mutex