default: clean

dir_ops:
	cc dir_ops.c -o dir_ops

exec_example:
	cc exec_example.c -o exec_example

processCreation:
	cc processCreation.c -o processCreation

process:
	cc process.c -o process

clean:
	rm *.o *.out dir_ops exec_example processCreation process